### ISSUE TITLE
password change broken

### ISSUE THREAD

**Issue by timum-viw** [team-olmen/olm_client#1]
Dich hats ja wieder richtig gepackt, mit Olmen, was? :D 
Ich kann im Moment mein Passwort nicht ändern. Es passiert einfach gar nichts, wenn ich auf speichern klicke.. vielleicht habe ich Zeit am Wochenende den Code mal auszuchecken und selbst mal reinzuschauen. Würde mich auf jeden Fall interessieren.

edit: Ah, habs gecheckt. Die Fehlermeldung kam erst nicht. der username darf kein @ enthalten. Das ist tricky, wenn die vorlage meine mail Adresse ist.

edit edit: achso, vielleicht wäre es noch gut ein passwort wiederholen feld zu haben.

**Comment by randomchars42** [comment]
Eigentlich sollte der linke Rahmen des Feldes, dass eine fehlerhafte EIngabe enthält rot sein, und darunter in blau ein Hinweis erscheinen. Zusätzlich sollte der "Speichern" Button ausgegraut sein. Zumindest FF 54 auf Ubuntu zeigt dieses Verhalten. Bin mir aber dessen bewusst, dass ich da ein bisschen ein exotischeres System habe ;) Wie schaut es bei dir aus?

**Comment by timum-viw** [comment]
Ah ja. Wenn ich etwas in das Feld eingebe, kommt der Fehler. Das Problem war nur, dass als Voreinstellung meine Email-Adresse als Benutzername angegeben war. Wenn ich daran nichts ändere, kommt auch keine Fehlermeldung. Speichern kann ich trotzdem nicht.

**Comment by randomchars42** [comment]
Danke für den Hinweis, das habe ich bis jetzt übersehen, weil ich wusste, dass man den Benutzernamen ändern muss ;)
ist natürlich taktisch unklug, dass nicht nochmal anzuzeigen... aber das lässt sich ändern ;)

**Comment by randomchars42** [comment]
fixed with: b3487a223ce3121d0bd4b07d6baf67e667fa6788 / v2.0.1 :-)
(hoffentlich ;-) )
