### ISSUE TITLE
pdfs hochladen?

### ISSUE THREAD

**Issue by dolaberf** [team-olmen/olm_client#10]
Hey,
gäbe es eine Möglichkeit, auf olmen einen Bereich einzurichten, in den pdfs hochgeladen werden können?
Da wir ja neuerdings die Testhefte mitnehmen können kann man die nachher einscannen, damit die nächsten eine optimale Übungsmöglichkeit haben. Die Frage ist natürlich auch, wie aufwendig das zu programmieren wäre. Ich hab davon keine Ahnung ;)
Als Beispiel:
https://www.dropbox.com/sh/kxvpxggqzhfxhko/AADymZAE0CiW0HVO4CtfdpS1a?dl=0
LG Rafael

**Comment by timum-viw** [comment]
Hey,

ich denke, es ist nicht der Sinn von Olmen, Prüfungsfragen als PDF anzubieten. Wenn dann sollten die Fragen richtig im System landen, denke ich. Sag gerne bescheid, wenn du das ganz anders siehst, aber bis dahin schließe ich das erstmal 😄
