### ISSUE TITLE
SSL Encryption

### ISSUE THREAD

**Issue by drs-m** [team-olmen/olm_client#12]
The web service should be protected by ssl/tls encryption as many students probably use the same password for OLM and for their university account. A free and easily deployable solution would be https://letsencrypt.org.

**Comment by timum-viw** [comment]
You're absolutely right. But we are hosting this on a really cheap package so we don't have access to deploy a certificate.. If you have other ideas to make this more secure please let us know. cheers

p.s. I actually tried to remove the passwords from our server altogether by getting some kind of Open ID thing from the university. They declined.. because of security issues..

**Comment by randomchars42** [comment]
Recently, the option to deploy your own certificate via the web-configuration tool has been made available by the provider. But afaik there's no way to automate certificate renewal... So you'd have to acquire the certificate locally (that's not so hard) and upload it manually. But you'd have to do it every so often (I don't know when validity expires).

**Comment by drs-m** [comment]
I assume you are currently using the cheapest managed hosting option available at HostEurope (at 3,99 € / mo). Depending on resource consumption one could consider moving to a vServer provider (for example digitalocean.com has really good prices). But the disadvantage would be to take care of things like DB backups and a mail server yourself. The problem with LetsEncrypt ssl certificates is that the expiration period is at most 90 days if I'm correct, so you would have to replace it quite often.

I think there really is no other way to make the website more secure besides configuring SSL encryption. If you have any kind of authentication - i.e. OpenID - you should always have a secure connection with either the user (or in that scenario the OpenID provider), right?

What we could consider doing is using a LetsEncrypt certificate and updating it automatically using a different server which has FTP access to the webhost or a HTTP redirect. I've no experience with this but it seems like it should be quite possible (https://community.letsencrypt.org/t/automate-cert-renewal-from-different-server/30592).

**Comment by timum-viw** [comment]
Actually open id only needs ssl on the provider side since no confidential information is ever shared on a direct connection from the user to the consumer.
I've sent you an invite to our slack channel. We can further discuss this there.
