### ISSUE TITLE
https

### ISSUE THREAD

**Issue by timum-viw** [team-olmen/olm_client#2]
meinst du es wäre aufwendig den server auf https umzustellen?

**Comment by randomchars42** [comment]
aufwendig garnicht. Ist eher eine Frage der Kosten, da das derzeitige Webpack keine SSL-Zertifikate erlaubt. Man könnte alles über https://ssl.webpack.de/api.olmen.de bzw. https://ssl.webpack.de/olmen.de umleiten, ich weiß aber nicht wie umständlich das wird. Da der Server nun der FSI gehört, müssten man das mal dem Webmaster diskutieren.

**Comment by timum-viw** [comment]
Das hab ich mir schon fast gedacht. Umleiten klingt blöd. Webmaster fragen klingt besser 😃
