### ISSUE TITLE
Anmeldemaske

### ISSUE THREAD

**Issue by kotarokun** [team-olmen/olm_client#6]
Nochmal ich..
das problem derzeit bei der Anmeldemaske ist, wenn man sich beim Passwort vertippt hat, muss man das Passwort ALS AUCH Benutzername ändern (z.b. ein Buchstaben hinzufügen und wieder entfernen)
Da sollte es doch ausreichen, nur eins ändern zu müssen ;)

**Comment by randomchars42** [comment]
Das ist so irgendwo zwischen Feature und Bug ;)

Um anzuzeigen, dass Nutzername *oder* Passwort falsch sein könnten, werden beide Felder auf "invalid" gesetzt. Um die Maske abschicken zu können muss, wie Du beschreibst, ein change-Event in jedem der Felder ausgelöst werden...

Man könnte das sehr leicht umstellen, sodass die Fehlermeldung nur unter dem PW-Feld angezeigt wird und das Username-Feld valide bleibt, ist eher eine inhaltliche Entscheidung - bin da aber offen für alles ( @timum-viw ?) ;)

Es geht um folgende Zeile, die ggf. zu löschen wäre:
https://github.com/randomchars42/olm_client/blob/5d6c26378be9c34cdca5dbaa885e82f5a0f54fdd/src/app/core/door.component.ts#L70

**Comment by timum-viw** [comment]
ist gefixt
